### ISSUE TITLE
求kindle原生系统支持格式~~~ 现在499 kindle还不能刷多看，自己转换的mobi或者azw3都不是弹出式注解

### ISSUE THREAD

**Issue by drcege** [sadhen/shiji#1]

**Comment by da-liii** [comment]
等这段时间考试考完试试看

**Comment by ghost** [comment]
求epub看

**Comment by da-liii** [comment]
@addio 
http://home.ustc.edu.cn/~sadhen/kindle/shiji.epub
这个是最新的epub

**Comment by da-liii** [comment]
@addio

现在你可以用代码直接生成epub了

**Comment by da-liii** [comment]
@mwlgcmwlgc 
http://home.ustc.edu.cn/~sadhen/kindle/shiji.mobi
这个是最新的mobi，适用于原生系统

针对现在的代码，将main函数里面的isMOBI置为True
这样生成shiji.epub后，在用Calibre将epub转为mobi(这个可能需要为Calibre装一个插件)
